Repository rond-authz/rond, pull requests merged in 2023-07, with the labels that each got.

#217 feat: use crud client lib
  go.mod
  go.sum
  helpers/headers_to_proxy.go
  helpers/headers_to_proxy_test.go
  internal/crudclient/crudclient.go
  internal/crudclient/crudclient_test.go
  internal/crudclient/testing.go
  internal/helpers/gracefulshutdown.go
  internal/helpers/gracefulshutdown_test.go
  internal/helpers/headers_to_proxy.go
  internal/helpers/headers_to_proxy_test.go
  main.go
  service/router.go
  service/standalone_apis.go
  service/standalone_apis_test.go
  types/rbactypes.go
Labels: bug, refactor

#219 New FromConfig SDK
  core/errors.go
  core/opaevaluator.go
  core/opaevaluator_test.go
  core/partialevaluators.go
  core/partialevaluators_test.go
  core/print.go
  core/print_test.go
  core/utils.go
  core/utils_test.go
  internal/fake/sdk.go
  main.go
  main_test.go
  mocks/rego-policies-with-mongo-builtins/example.rego
  openapi/evaluators.go
  openapi/evaluators_test.go
  openapi/openapi_utils.go
  openapi/openapi_utils_test.go
  sdk/context_test.go
  sdk/evaluator.go
  sdk/evaluator_test.go
  sdk/openapi.go
  sdk/openapi_test.go
  sdk/sdk.go
  sdk/sdk_test.go
  service/handler.go
  service/handler_test.go
  service/opa_transport_test.go
  service/opamiddleware.go
  service/opamiddleware_test.go
  service/router_test.go
  service/statusroutes_test.go
Labels: enhancement

#220 feat: use rond logger instead of logrus
  core/input.go
  core/input_test.go
  core/opaevaluator.go
  core/opaevaluator_test.go
  core/partialevaluators.go
  core/partialevaluators_test.go
  core/utils.go
  core/utils_test.go
  go.mod
  go.sum
  internal/mongoclient/mongoclient.go
  internal/mongoclient/mongoclient_test.go
  logging/logger.go
  logging/logrus/logger.go
  logging/logrus/logger_test.go
  logging/test/logger.go
  logging/test/logger_test.go
  main.go
  main_test.go
  openapi/evaluators.go
  openapi/evaluators_test.go
  openapi/openapi_utils.go
  openapi/openapi_utils_test.go
  sdk/evaluator.go
  sdk/evaluator_test.go
  sdk/openapi.go
  sdk/openapi_test.go
  sdk/sdk.go
  sdk/sdk_test.go
  service/handler.go
  service/handler_test.go
  service/opa_transport.go
  service/opa_transport_test.go
  service/opamiddleware.go
  service/opamiddleware_test.go
  service/router.go
  service/router_test.go
  service/standalone_apis.go
  service/statusroutes.go
  service/statusroutes_test.go
  types/rbactypes.go
Labels: refactor

#227 feat: update metrics
  core/opaevaluator.go
  core/partialevaluators_test.go
  go.mod
  internal/metrics/metrics.go
  internal/metrics/metrics_test.go
  main.go
  main_test.go
  metrics/metrics.go
  metrics/prometheus/prom.go
  metrics/prometheus/prom_test.go
  metrics/test/metrics.go
  sdk/evaluator_test.go
  sdk/openapi.go
  sdk/openapi_test.go
  sdk/sdk.go
  sdk/sdk_test.go
  service/metricsroute.go
  service/metricsroute_test.go
  service/opa_transport_test.go
  service/router.go
  service/router_test.go
  service/statusroutes_test.go
Labels: refactor

#232 feat(#207): add user id to input struct
  core/input.go
  main_test.go
  mocks/rego-policies/example.rego
  mocks/simplifiedMock.json
  openapi/evaluators_test.go
  openapi/openapi_utils_test.go
  sdk/evaluator_test.go
  sdk/rondinput/http/input.go
  sdk/rondinput/http/input_test.go
  sdk/sdk_test.go
Labels: enhancement
