Repository rond-authz/rond, pull requests merged in 2023-08, with the labels that each got.

#235 ci: new job names
  .github/workflows/test.yml
Labels: github_actions

#243 Improve SDK interface
  core/input.go
  core/opaevaluator.go
  core/opaevaluator_test.go
  core/partialevaluators.go
  core/partialevaluators_test.go
  custom_builtins/mocks/mongoclient.go
  custom_builtins/mongo.go
  custom_builtins/mongoclient.go
  custom_builtins/mongoclient_test.go
  internal/fake/inputuser.go
  internal/fake/sdk.go
  internal/mocks/evaluator.go
  internal/mongoclient/mongoclient.go
  internal/mongoclient/mongoclient_test.go
  main.go
  main_test.go
  mocks/rego-policies-with-mongo-builtins/example.rego
  sdk/README.md
  sdk/evaluator.go
  sdk/evaluator_test.go
  sdk/inputuser/client.go
  sdk/inputuser/client_test.go
  sdk/inputuser/mongo/mongoclient.go
  sdk/inputuser/mongo/mongoclient_test.go
  sdk/inputuser/user.go
  sdk/inputuser/user_test.go
  sdk/integration_test.go
  sdk/openapi.go
  sdk/openapi_test.go
  sdk/rondinput/http/input.go
  sdk/rondinput/http/input_test.go
  sdk/sdk.go
  sdk/sdk_test.go
  service/handler.go
  service/handler_test.go
  service/opa_transport.go
  service/opa_transport_test.go
  service/opamiddleware.go
  service/router.go
  service/router_test.go
  service/standalone_apis_test.go
  service/statusroutes_test.go
  types/rbactypes.go
Labels: enhancement

#250 feat: improve sdk request evaluator interface
  core/errors.go
  core/opaevaluator.go
  core/partialevaluators_test.go
  internal/fake/sdk.go
  sdk/evaluator.go
  sdk/evaluator_test.go
  service/handler.go
  service/router_test.go
Labels: enhancement

#251 fix: send empty filter header
  sdk/evaluator.go
  sdk/evaluator_test.go
  sdk/integration_test.go
  sdk/sdk_test.go
  service/handler.go
  service/handler_test.go
Labels: bug
