Repository rond-authz/rond, pull requests merged in 2024-10, with the labels that each got.

#395 Fix mssing " in cosign step
  .github/workflows/test.yml
Labels: github_actions

#394 perf: prepare partial evaluation at boot for better performances
  core/input.go
  core/input_test.go
  core/opaevaluator.go
  core/opaevaluator_test.go
  core/partialevaluators.go
  core/partialevaluators_test.go
  core/rego.go
  core/rego_test.go
  sdk/evaluator.go
Labels: enhancement, performance

#397 feat: migrate envs lib
  go.mod
  go.sum
  internal/config/env.go
  main.go
  main_test.go
Labels: dependencies, refactor

#398 ci: drop go1.21 test support for EOL
  .github/workflows/test.yml
Labels: github_actions

#399 refactor: improve main tests
  main.go
  main_test.go
  service/sdkbootstate.go
  service/sdkbootstate_test.go
  service/statusroutes.go
Labels: refactor

#400 feat: add compiler to filter policies
  Makefile
  core/opaevaluator.go
  core/partialevaluators_test.go
  core/rego.go
  core/rego_test.go
  integration_test.go
  main.go
  main_test.go
  mocks/crudServiceMock.json
  sdk/evaluator_test.go
  sdk/openapi_test.go
  sdk/sdk_test.go
  service/handler_test.go
  service/opa_transport_test.go
  service/opamiddleware_test.go
  service/router_test.go
  service/statusroutes_test.go
Labels: enhancement, performance
