Repository rond-authz/rond, pull requests merged in 2025-01, with the labels that each got.

#419 fix: resolve concurrent map writes for audit cache
  internal/audit/agent.go
  internal/audit/agent_log.go
  internal/audit/agent_log_test.go
  internal/audit/agent_test.go
  internal/audit/cache.go
  logging/test/logger.go
  sdk/audit_factory.go
  sdk/audit_factory_test.go
  sdk/evaluator.go
  sdk/evaluator_test.go
  sdk/openapi.go
  sdk/openapi_test.go
  sdk/sdk.go
Labels: bug

#403 ci: remove test util files from coverage
  .covignore
  Makefile
Labels: github_actions

#432 feat: filter audit trails based on configuration file
  internal/audit/agent_compound.go
  internal/audit/agent_compound_test.go
  internal/audit/agent_log.go
  internal/audit/agent_log_test.go
  internal/audit/agent_mongodb.go
  internal/audit/agent_mongodb_test.go
  internal/audit/agent_pool.go
  internal/audit/config.go
  internal/audit/config_test.go
  internal/audit/filter.go
  internal/audit/filter_test.go
  internal/config/env.go
  internal/config/env_test.go
  main.go
  main_test.go
  mocks/audit-configurations/config.json
  sdk/audit_factory.go
  sdk/sdk.go
Labels: enhancement

#433 fix: make audit config file optional
  internal/config/env.go
  internal/config/env_test.go
  main.go
Labels: bug

#434 test: added get headers builtin tests
  custom_builtins/get_header.go
  custom_builtins/get_header_test.go
Labels: technical debt
